---
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:3.10.0
    container_name: ddclient
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Etc/UTC
    volumes:
     - ddclient-config:/config
    restart: unless-stopped
  pihole:
    image: pihole/pihole:2023.10.0
    container_name: pihole
    ports:
     - "192.168.50.153:53:53/tcp"
     - "192.168.50.153:53:53/udp"
     - "192.168.50.153:67:67/udp"
     - "192.168.50.153:80:80/tcp"
    environment:
     - TZ=America/New_York
     - FTLCONF_LOCAL_IPV4=192.168.50.153
    volumes:
     - pihole-etc:/etc/pihole
     - pihole-dnsmasq:/etc/dnsmasq.d
    cap_add:
     - NET_ADMIN
    restart: unless-stopped
volumes:
  ddclient-config: {}
  pihole-etc: {}
  pihole-dnsmasq: {}
