---
services:
  certbot:
    image: tsachleben/crond-certbot:latest
    container_name: certbot
    environment:
      - TZ=Etc/UTC
    volumes:
      - tls-certs:/etc/letsencrypt
      - tls-archive-ntfy:/etc/letsencrypt/archive/ntfy.sachleben.me
      - tls-live-ntfy:/etc/letsencrypt/live/ntfy.sachleben.me
      - tls-archive-vaultwarden:/etc/letsencrypt/archive/vaultwarden.sachleben.me
      - tls-live-vaultwarden:/etc/letsencrypt/live/vaultwarden.sachleben.me
    networks:
      - mgmt
    restart: unless-stopped
  # dex:
  #   image: dexidp/dex:v2.37.0
  #   container_name: dex
  #   environment:
  #     - TZ=Etc/UTC
  #     - DEX_TELEMETRY_HTTP="0.0.0.0:5557"
  #   volumes:
  #     - dex-etc:/etc/dex
  #   networks:
  #     wg_bridge:
  #       ipv4_address: 172.16.1.5
  #   restart: unless-stopped
  vaultwarden:
    image: vaultwarden/server:1.29.2-alpine
    container_name: vaultwarden
    environment:
      - TZ=Etc/UTC
      - ROCKET_PORT=443
      - ROCKET_TLS={certs="/etc/letsencrypt/live/vaultwarden.sachleben.me/fullchain.pem",key="/etc/letsencrypt/live/vaultwarden.sachleben.me/privkey.pem"}
    volumes:
      - tls-archive-vaultwarden:/etc/letsencrypt/archive/vaultwarden.sachleben.me
      - tls-live-vaultwarden:/etc/letsencrypt/live/vaultwarden.sachleben.me
      - vaultwarden-data:/data
    networks:
      wg_bridge:
        ipv4_address: 172.16.1.3
    restart: unless-stopped
  ntfy:
    image: binwiederhier/ntfy:v2.7.0
    command:
      - serve
    container_name: ntfy
    environment:
      - TZ=Etc/UTC
      - NTFY_BASE_URL=http://ntfy.sachleben.me
      - NTFY_LISTEN_HTTPS=:443
      - NTFY_KEY_FILE=/etc/letsencrypt/live/ntfy.sachleben.me/privkey.pem
      - NTFY_CERT_FILE=/etc/letsencrypt/live/ntfy.sachleben.me/fullchain.pem
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_CACHE_DURATION=168h
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT=1G
      - NTFY_ATTACHMENT_FILE_SIZE_LIMIT=50M
      - NTFY_ATTACHMENT_EXPIRY_DURATION=24h
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
    volumes:
      - ntfy-etc:/etc/ntfy
      - ntfy-lib:/var/lib/ntfy
      - ntfy-cache:/var/cache/ntfy
      - tls-archive-ntfy:/etc/letsencrypt/archive/ntfy.sachleben.me
      - tls-live-ntfy:/etc/letsencrypt/live/ntfy.sachleben.me
    networks:
      wg_bridge:
        ipv4_address: 172.16.1.4
    restart: unless-stopped
volumes:
  # dex-etc: {}
  tls-certs: {}
  tls-archive-ntfy: {}
  tls-live-ntfy: {}
  tls-archive-vaultwarden: {}
  tls-live-vaultwarden: {}
  vaultwarden-data: {}
  ntfy-etc: {}
  ntfy-lib: {}
  ntfy-cache: {}
networks:
  wg_bridge:
    external: true
  mgmt: {}
