---
services:
  vaultwarden:
    image: vaultwarden/server:1.29.2-alpine
    container_name: vaultwarden
    environment:
      - TZ=Etc/UTC
    volumes:
      - vaultwarden-data:/data
    networks:
      - wg_bridge
    restart: unless-stopped
  ntfy:
    image: binwiederhier/ntfy:v2.7.0
    command:
      - serve
    container_name: ntfy
    environment:
      - TZ=Etc/UTC
      - NTFY_BASE_URL=http://ntfy.sachleben.me
      # - NTFY_LISTEN_HTTPS=:443
      - NTFY_BEHIND_PROXY=true
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_CACHE_DURATION=168h
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT=1G
      - NTFY_ATTACHMENT_FILE_SIZE_LIMIT=50M
      - NTFY_ATTACHMENT_EXPIRY_DURATION=24h
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
    volumes:
      - ntfy-etc:/etc/ntfy
      - ntfy-lib:/var/lib/ntfy
      - ntfy-cache:/var/cache/ntfy
    networks:
      - wg_bridge
    restart: unless-stopped
volumes:
  vaultwarden-data: {}
  ntfy-etc: {}
  ntfy-lib: {}
  ntfy-cache: {}
networks:
  wg_bridge:
    external: true