---
services:
  vaultwarden:
    image: vaultwarden/server:1.29.2-alpine
    container_name: vaultwarden
    environment:
      - TZ=Etc/UTC
    volumes:
      - vaultwarden-data:/data
    networks:
      - wg_bridge
    restart: unless-stopped
volumes:
  vaultwarden-data: {}
networks:
  wg_bridge:
    external: true