---
services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    volumes:
      - mongodb:/data/db
    networks:
      - wg_bridge
    restart: unless-stopped
volumes:
  mongodb: {}
networks:
  wg_bridge:
    external: true