---
version: "3.8"
services:
  mongo:
    image: mongo:5.0.25
    container_name: mongo
    volumes:
      - mongodb:/data/db
    networks:
      - wg_bridge
    restart: unless-stopped
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.8
    container_name: homepage
    networks:
      - wg_bridge
    volumes:
      - homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
  freshrss:
    image: freshrss/freshrss:
    container_name: freshrss
    environment:
      - TZ=Europe/Paris
      - CRON_MIN=1,31
    volumes:
      - freshrss:/var/www/FreshRSS
    networks:
      - wg_bridge
    restart: unless-stopped
volumes:
  mongodb: {}
  homepage-config: {}
  freshrss: {}
networks:
  wg_bridge:
    external: true
