name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - run: |
        cat << __EOF >> $GITHUB_ENV
        IMAGE_TAG=tsachleben/crond-certbot:$(date +%s)
        __EOF
    - run: docker build . --file library/crond-certbot/Dockerfile --tag ${{ env.IMAGE_TAG }}
    - uses: docker/login-action@v1
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker push ${{ env.IMAGE_TAG }}
